### ISSUE TITLE
SEGV at startup

### ISSUE THREAD

**Issue by TheDevtop** [TheDevtop/rootve#5]
```
2023/11/24 13:37:56 Starting RootVE Server...
2023/11/24 13:37:56 Registered server endpoint
2023/11/24 13:37:56 Initialized table and configuration
2023/11/24 13:37:56 Autobooted website
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x61d410]

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x0, {0x6b4488, 0xa}, {0x728940?, 0x6e32e0})
        /usr/pkg/go120/src/net/http/server.go:2506 +0x50
net/http.(*ServeMux).HandleFunc(...)
        /usr/pkg/go120/src/net/http/server.go:2553
main.main()
        /home/thijs/rootve/rootd/rootd.go:48 +0x187
```
I don't know what is going wrong here.

**Comment by TheDevtop** [comment]
Fixed: a6c9ae640322ac7574faa8c1b57f00fa8e97306e
